version: '3'

services:
  ironfunctions01:
    restart: always
    image: iron/functions
    depends_on:
      - db
  db:
    image: postgres:12
    ports:
      - "5432:5432"
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
