services:
  mysrv:
    command:
      - appwrite/appwrite:0.10.4
    image: ','
    stdin_open: true
    tty: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${pwd}/appwrite:/usr/src/code/appwrite:rw
    restart: always
version: '3'
