etebase:
  container_name: etebase
  image: cvhariharan/etebase:v0.7.0-146-gd115040
  environment:
    ADMIN_USER: admin
    ADMIN_EMAIL: admin@example.com
    ADMIN_PASSWORD: password@123
  ports:
    - "5000:3735"
  volumes:
    - './etebase:/data'
