version: '2'
networks:
  app-tier:
    driver: bridge

services:
  nginx:
    build: ./nginx/
    links:
      - keystone
    networks:
      - app-tier
    ports:
      - "8080:80"
  mongodb:
    build: ./db
    volumes:
      - ./db/mongodb:/var/lib/mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGODB_USERNAME=${MONGODB_USERNAME}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
      - MONGODB_DATABASE=${MONGODB_DATABASE}
      - MONGODB_ROOT_USERNAME=${MONGODB_ROOT_USERNAME}
      - MONGODB_ROOT_PASSWORD=${MONGODB_ROOT_PASSWORD}
    networks:
      - app-tier

  keystone:
    build:
      context: ./keystone
      args:
        app_env: ${APP_ENV}
    volumes:
      - ./keystone/keystone.js:/usr/src/app/keystone.js
      - ./keystone/models:/usr/src/app/models
      - ./keystone/routes:/usr/src/app/routes
      - ./keystone/updates:/usr/src/app/updates
    ports:
      - "3000:3000"
    links:
      - mongodb
    networks:
      - app-tier
