version: '3.6'
services:
  postgres:
    image: postgres:12
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
  appsmith:
    image: index.docker.io/appsmith/appsmith-ce
    container_name: appsmith
    ports:
      - "80:8080"
      - "443:443"
      - "9001:9001"
    depends_on:
      - "postgres"
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    restart: unless-stopped
  auto_update:
    image: containrrr/watchtower:latest-dev
    command: --schedule "0 0 * ? * *" --label-enable --cleanup
    restart: unless-stopped
volumes:
  db_data:
